version: "3"
services: 
  react-app: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    image: sergiopichardo/react-app:latest
    ports: 
        - "3000:3000"
    volumes: 
        - /app/node_modules
        - .:/app
    stdin_open: true